import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Game from '../basic mincraft clone/components/Game/Game'

const inter = Inter({ subsets: ['latin'] })

export default function MineCraft() {
  return (
    <>
      <Head>
        <title>Minecraft</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Game/>
    </>
  )
}
